apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleapi-deployment
spec:
  selector:
    matchLabels:
      app: littleapi
  template:
    metadata:
      labels:
        app: littleapi
    spec:
      containers:
      - name: littleapi
        image: ronkilav/littleapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: littleapi-service
#   namespace: default
#   labels:
#     app: littleapi
# spec:
#   # externalTrafficPolicy: Cluster
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   selector:    
#     app: littleapi
#     type: NodePort

