apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleapi-deploy
  labels:
    app: littleapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: littleapi-deploy
  template:
    metadata:
      labels:
        app: littleapi-deploy
    spec:
      containers:
      - name: littleapi-deploy
        image: ronkilav/littleapi:latest

---
apiVersion: v1
kind: Service
metadata:
  name: littleapi-service
  labels:
    app: little-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: littleapi-deploy
